# The URL the site will be built for
base_url = "https://fy.blackhats.net.au"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Create rss
generate_feed = true

theme = "oceanic-zen"

title = "Firstyear's blog-a-log"
description = "Firstyear's blog"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "William Brown"
github = "firstyear"

